server {
    listen 80;
    listen [::]:80;
    # server_name streetpower.ru www.streetpower.ru;
	
	location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
		try_files $uri $uri/ /index.html;
        
        # Kill cache
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;
    }

    location = /training {
        root   /usr/share/nginx/html;
        try_files /training.html =404;
    }

    location ~ ^/training/info/?$ {
        root   /usr/share/nginx/html;
        try_files /training/info/index.html =404;
    }

    location ~ ^/training/([1-7])/?$ {
        root   /usr/share/nginx/html;
        try_files /training/$1/index.html =404;
    }
	
    # return 301 https://$server_name$request_uri;
}

# server {
#     listen 443 ssl;
#     listen [::]:443 ssl;
#     server_name streetpower.ru www.streetpower.ru;

#     http2 on;

#     ssl_certificate /certs/streetpower.crt;
#     ssl_certificate_key /certs/streetpower.key;
#     ssl_protocols TLSv1.2 TLSv1.3;
#     ssl_prefer_server_ciphers on;
#     ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
#     ssl_session_cache shared:SSL:10m;
#     ssl_session_tickets off;

#     location / {
#         root   /usr/share/nginx/html;
#         index  index.html index.htm;
# 		try_files $uri $uri/ /index.html;
#     }
# }
